### ISSUE TITLE
v-wave center not accurate on page with different { zoom } style

### ISSUE THREAD

**Issue by ChrisRoss5** [justintaddei/v-wave#133]
Changing the page zoom with css makes the wave center positioned incorrectly.

To reproduce the issue:
go to https://justintaddei.github.io/v-wave/
add { zoom: 0.5; } on body

**Comment by justintaddei** [comment]
Hi Chris. As MDN states, this is a not-standard property:

> <sub>https://developer.mozilla.org/en-US/docs/Web/CSS/zoom</sub>
> ## Non-standard
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

I've located a [chromium bug ticket regarding this behavior](https://bugs.chromium.org/p/chromium/issues/detail?id=429140#c8).  
Since there is no spec for `zoom` the bug ticket has been marked as `WontFix`

What is your use case for using `zoom`?

**Comment by ChrisRoss5** [comment]
Thanks for the quick response!
Also, thanks for the links!

I use `zoom` as an easy solution for smaller non-standard screen resolutions... basically **emulating** the browser zoom (crtl+-).

I'm sad how such an important feature is non-standard. I really didn't know. It saved me a bunch of time because my app is big and I didn't have to use millions of @mixins for many screen sizes.

**Comment by justintaddei** [comment]
That's an interesting use case. If I could find a clean way to solve this, I wouldn't mind publishing a patch. Unfortunately, the only solution I have found relies on `getComputedStyle(elWithZoom).zoom` which would require knowing in advance which element(s) have zoom applied + the performance overhead of `getComputedStyle`, which is actually quite a lot (as I've learned from my work on _v-shared-element_).

With that said, I've never worked with the `zoom` before. Do you have any other ideas to get around this?

**Comment by ChrisRoss5** [comment]
Sounds like too much work for something that's non-standard. Thank you very much for giving it a chance, you should forget about it until it hopefully becomes a standard. For now, I'll try to control it with a global vue boolean variable, like so
 `:v-wave="noPageZoom"`

**Comment by justintaddei** [comment]
I'm going to close this as `won't fix` for now. Feel free to reopen it if you come across any other solutions!
