### ISSUE TITLE
Incorrect typings for vue 2

### ISSUE THREAD

**Issue by satanshiro** [justintaddei/v-wave#191]
vue 2 has declared type for "PluginObject" and "PluginFunction" no typings for plain "Plugin".
this will fail builds that don't have in their tsc compiler options  "skipLibCheck": true

**Comment by justintaddei** [comment]
Thank you. I'll check into that within the next few days!

**Comment by rosenfeldalon** [comment]
Happens to me as well

"vue": "^2.6.14",
"v-wave": "^1.3.1",

`ERROR in XXX/node_modules/v-wave/dist/types/index.d.ts(1,10):
1:10 Module '"vue"' has no exported member 'Plugin'. Did you mean to use 'import Plugin from "vue"' instead?
  > 1 | import { Plugin } from 'vue';
      |          ^
    2 | declare const VWave: Plugin & {
    3 |     installed: boolean;
    4 | };
`

Regards

**Comment by justintaddei** [comment]
Fixed in [`v1.3.2`](https://www.npmjs.com/package/v-wave/v/1.3.2)

Thank you all for your help on this issue.

**Comment by satanshiro** [comment]
hey @justintaddei 
I have updated the package but there is a different small bug
![image](https://user-images.githubusercontent.com/38865738/141778382-e3e2e510-17dd-4dc1-9a5c-8293b72b444e.png)
![image](https://user-images.githubusercontent.com/38865738/141778430-13bc1f32-0052-4579-9ac1-7119656b0b5b.png)
as you can see clients receive only the distribution and src/options does not exist the d.ts only needs the typing

**Comment by justintaddei** [comment]
Thank you for bringing this to my attention! I will look into it and likely publish a patch by this evening

**Comment by justintaddei** [comment]
@satanshiro @rosenfeldalon release `v1.3.3`  should resolve these additional issues. Please let me know if you experience any other problems!
