### ISSUE TITLE
Option to change the html tag generated

### ISSUE THREAD

**Issue by justintaddei** [justintaddei/v-wave#281]
### Discussed in https://github.com/justintaddei/v-wave/discussions/280

<div type='discussions-op-text'>

<sup>Originally posted by **kleine-b-avt** March 14, 2022</sup>
It would be nice to have this option, in cases when we have to use last-of-type css selectors.</div>

**Comment by justintaddei** [comment]
@kleine-b-avt thoughts?

Purposed API:

```vue
<button v-wave="{
  containerElementTag: 'span'
}">
Click me!
</button>
```
Result:
```vue
<button v-wave="{
  containerElementTag: 'span'
}">
Click me!
<span style="..."> <!-- container element -->
  <div style="..."></div> <!-- wave element -->
</span>
</button>
```

Please let me know if you have any ideas to improve this!

**Comment by kleine-b-avt** [comment]
It could be that. or it could be that the span is the wave element itself. Either way, both works for the purpose intended.

**Comment by justintaddei** [comment]
@kleine-b-avt the container is already part of the current implementation. It's used to apply `overflow: hidden`  in a manner that doesn't change the appearance of the host element.

**Comment by kleine-b-avt** [comment]
Oh, ok. Got it. Your initial solution is perfect. 
Thanks for the prompts responses.
