### ISSUE TITLE
Improve documentation (suggestions welcome!)

### ISSUE THREAD

**Issue by justintaddei** [justintaddei/v-wave#296]
Improve documentation with clearer examples and gifs

#### Additions to be made:
- document use of `radial-gradient` and similar advanced effects.

**Comment by mdmomeni** [comment]
Hey, for instance, there's a radial gradient style in the basic examples of the demo page that I didn't find anything about its options

**Comment by justintaddei** [comment]
@mdmomeni  thank you, I'll add that to the list! If you want to use it before I release the updated docs, I achieved that effect simply by setting the color to a css radial gradient. It works very well because the initial size of the element used for the wave is its maximum size, from which is scaled down and the animated back to the original (maximum) size; thus no distortion or pixelation of the rasterized gradient.
