### ISSUE TITLE
Please update to Vue 3

### ISSUE THREAD

**Issue by Nais0ne** [justintaddei/v-wave#3]
Vue 3 has breaking changes for directives (renamed hooks)

https://v3.vuejs.org/guide/migration/custom-directives.html#_2-x-syntax

**Comment by justintaddei** [comment]
My apologies for the delayed reply. I didn't see the notification come in 😬

I'll release an update either tonight or tomorrow!

**Comment by justintaddei** [comment]
Experimental support for Vue 3 is now available!

Install it with : `npm i v-wave@next`

Please let me know if you experience any issues after upgrading. I still have to determine how I will continue to support Vue 2 while also supporting Vue 3. Once I have figured out how to best go about that I will release support for Vue 3 in the stable channel.

**Comment by justintaddei** [comment]
Vue 3 is now supported as of `v1.2.0`
