### ISSUE TITLE
Any way to use this effect on pure HTML/JS?

### ISSUE THREAD

**Issue by Christian-Martinez1** [justintaddei/v-wave#309]
Hello,

I want to eventually learn the Vue framework but for now I am using simply HTML,CSS,JS to do relatively basic web applications. I am using Tailwind CSS with the Tailwind UI component library for beautiful looking components, however they do not come with any click animations and was wondering if there is a way I can use your v-wave effect on standard HTML/JS?

**Comment by justintaddei** [comment]
Not at the moment, but I am currently working on splitting the actual wave effect into another module that can be used with vanilla js. My motivation to do this was to share the codebase between v-wave and use-wave (the react.js version) but it would also serve your needs.

I'm going to close this issue for now, but I will ping you after it is released

**Comment by Christian-Martinez1** [comment]
> Not at the moment, but I am currently working on splitting the actual wave effect into another module that can be used with vanilla js. My motivation to do this was to share the codebase between v-wave and use-wave (the react.js version) but it would also serve your needs.
> 
> I'm going to close this issue for now, but I will ping you after it is released

Awesome, that would be sick mate! Thank you, I appreciate your work as I like how your ripple effect functions far more than the standard Vue effect.

**Comment by Christian-Martinez1** [comment]
Hey bro, any update on how the vanilla js version is coming along?
