### ISSUE TITLE
`v-wave` directive doesn't seem to react to the boolean variable

### ISSUE THREAD

**Issue by DamianGlowala** [justintaddei/v-wave#535]
When `:v-wave='true'`, the directive appears to be turned off.

Vue template:
```
<button :v-wave="!disabled" />
```

Vue script:
```
const disabled = ref(true)
```

**Comment by justintaddei** [comment]
Thank you. I'll investigate tomorrow

**Comment by justintaddei** [comment]
This doesn't appear to be an issue with v-wave. You've written `:v-wave=` which is invalid. You should use `v-wave=` (no colon `:`). Also, if `const disabled = ref(true)` then `!disabled` would be `false` so  `<button v-wave="!disabled" />` would actually be disabled.
