### ISSUE TITLE
Wave effect on keypress (Enter)

### ISSUE THREAD

**Issue by JaxThePrime** [justintaddei/v-wave#686]
Hi, i've ben using this package for a while and it works perfectly fine, although i think it would be nice if it worked on keyboard events like keypress Enter on a button and stuff like that hope you concider adding it in the future

**Comment by justintaddei** [comment]
Thank you for the suggestion! I'll look into including this in the next release.

**Comment by justintaddei** [comment]
Progress is underway. This is the last feature planned before the v3.0.0 release

**Comment by justintaddei** [comment]
There are a few things left that need to be cleaned up before the v3 release. I'm going on a trip this week so I'm targeting the first week of August for the release.

**Comment by a145789** [comment]
Hello, are there any new releases planned for the near future?I really need the `disabled` feature of `v3.0`

**Comment by justintaddei** [comment]
@a145789 Yes, before the end of August. Work has been busy so I haven't had time to finalize v3.0 yet, but it's almost there :)

**Comment by justintaddei** [comment]
@a145789 it's still August, right? 😂

I just published v3.0.0!

**Comment by a145789** [comment]
@justintaddei  That's so cool, thanks for your work
