### ISSUE TITLE
How unbind directive

### ISSUE THREAD

**Issue by Gumper-x** [justintaddei/v-wave#69]
If pass "flase":
![image](https://user-images.githubusercontent.com/52721424/113445459-970b2b80-93fe-11eb-94cb-37579b022ea5.png)
It continues to work.

Pls help:
How dynamically disable this directive?

**Comment by justintaddei** [comment]
Unbinding a directive without removing the element entirely is not really a normal thing to do in a Vue app.

Would you mind sharing your use case?
I'd be open to creating a new feature to provide a disabling mechanism but I need to know how you intend to use it first.

Thank you.

**Comment by Gumper-x** [comment]
@justintaddei  I want to transmit a prop from which I will bind or unbind "v-wave"
Something like this:
```vue
<template>
  <button v-wave="getRipple">TEXT</button>
</template>

<script>
  export default {
    props: {
      ripple: {
        type: Boolean,
        default: false,
      },
    },
    computed: {
      getRipple() {
        const opacity = {
          duration: 0.35,
          easing: "ease-in-out",
        };
        return this.ripple ? opacity : false;
      },
    },
  };
</script>
```

**Comment by justintaddei** [comment]
I'll work this into the next release!

**Comment by justintaddei** [comment]
@Gumper-x v1.3.0 is out! You can now pass `false` to the directive to disable the wave effect!
