### ISSUE TITLE
Disabled wave effect if `prefers-reduced-motion:` set to `reduce`

### ISSUE THREAD

**Issue by erwanjugand** [justintaddei/v-wave#740]
Hi, 

I would like to request a new feature to enhance accessibility for users who [prefers reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). 

Like `respectDisabledAttribute`, it's possible to add a new condition before rendering the wave effects?

Maybe:  `respectUserPreference`

**Comment by justintaddei** [comment]
Absolutely. I'll include this in the v3.0.0 release!

**Comment by justintaddei** [comment]
I appreciate the suggestion! This feature is in `master` and will be in `v3.0.0` once released.
