### ISSUE TITLE
VWave.createLocalWaveDirective is not a function

### ISSUE THREAD

**Issue by DamianGlowala** [justintaddei/v-wave#788]
When building Nuxt for production, I am receiving the following error in SSR. This should be straightforward to replicate, but let me know if you need a reproduction. It does not happen in `v-wave` v2.0.0.

(`nuxt` v3.13.1, `v-wave` v3.0.1)

![image](https://github.com/user-attachments/assets/597579dc-7829-41b9-8c97-063124ba787d)

**Comment by justintaddei** [comment]
Thank you for the report! Please install `v-wave@^3.0.2` and let me know if you experience any other issues.
