### ISSUE TITLE
v-wave="false" no longer disables the effect

### ISSUE THREAD

**Issue by tchyra** [justintaddei/v-wave#816]
You can replicate this on the [live demo](https://justintaddei.github.io/v-wave/) by simply replacing the options with `false`.

```html
<div v-wave="false">
  Click here
</div>
```

Expected passing `false` to disable the effect, as described in issue #69 (https://github.com/justintaddei/v-wave/issues/69#issuecomment-876048478).

This library is great, thanks!

**Comment by justintaddei** [comment]
That functionality was removed in v3.0.0 in favor of the following methods:

```html
<!-- using the native html attribute -->
<button v-wave :disabled="isDisabled">
```
or
```html 
<!-- using the disabled optoin -->
<button v-wave="{ disabled: isDisabled }">
```

You can find more information here: https://github.com/justintaddei/v-wave?tab=readme-ov-file#disabled

**Comment by justintaddei** [comment]
Would you mind elaboration on this point?
> And it also doesn't require inverting for cases where I'd rather specify if the waves should be enabled instead of disabled,

It seems what you're describing is something like the following:

```vue
<script setup>
import { computed } from 'vue';

const name = ref('');
const isValidName = computed(() => name.length > 3);
</script>

<template>
<form>
  <input type="text" v-bind:name />
  <div @click="someSubmitLogic" v-wave="{disabled: !isValidName}">Submit</div>
</form>
</template>
```
Because `div`s don't support the `disabled` attribute, I've used the `disabled` option on the directive `{disabled: !isValidName}`

**Comment by tchyra** [comment]
> Would you mind elaboration on this point?

Yes, that is indeed the use case, I'm wondering why not keep the option to simply write `v-wave="isValidName"`. From my point of view:
- `disabled` is the only per-element option for the `v-wave` directive I needed so far, I imagine for most users it's either the only used option or the most used option. Having a more concise way to achieve the most common use case is useful.
- The `v-wave="boolean"` syntax is not hard to read or counter-intuitive, it reads similar to other attributes that take a boolean: `:checked="isChecked"`, `:hidden="isHidden"`, `v-wave="useWaves"`
- Respecting the native `disabled` attribute is great, because it saves duplicating the value from `:disabled` to `v-wave`, but it's not a 100% replacement for disabling the waves manually:
  - as previously mentioned, not all elements can have a `disabled` attribute,
  - elements that can have a `disabled` attribute like `<button>` can't be nested,
  - sometimes I might want to disable waves despite the element not being `disabled`.

This is not a matter of "I can't use the `v-wave="{ disabled: !isEnabled }"`" syntax instead of `v-wave="isEnabled"`", this is a matter of me finding the shorter syntax more convenient and not seeing a good reason as to why it was removed. If it's for a technical reason, I understand.

**Comment by justintaddei** [comment]
The motivations for removing it were:
- It didn't work correctly in v2 (sometimes the wave would still animate. This was discovered during development on v3 but I didn't investigate the cause).
- I felt having the `disabled` option instead of the `boolean` was more consistent with the rest of the library. 
- Since it was already a major release, it seemed the best time to change it.

On the point of consistency, I felt it was better to have a unified way of disabling the wave. The idea was to not have three different ways to disable it, one of which being inverted.

In the following example, `valid` and `!valid` both disable the wave depending on the context.

```vue
<script setup>
import { computed } from 'vue';

const name = ref('');
const valid= computed(() => name.length > 3);
</script>

<template>
<form>
  <input type="text" v-bind:name />
  <button @click="someSubmitLogic" v-wave :disabled="!valid">Submit</div>
  <div @click="checkNameTaken" v-wave="valid">Check availablity</div>
  <!-- yet another way to disable the wave: -->
  <div @click="name = ''" v-wave="{
    color: 'red',
    disabled: name === ''
  }">Clear</div>
</form>
</template>
```

Removing the option forced both cases to read the same way:

```vue
<button @click="someSubmitLogic" v-wave :disabled="!valid">Submit</div>
<div @click="checkNameTaken" v-wave="{disabled: !valid}">Check availablity</div>
```

I don't personally feel like the introduction of a third, inconsistent manner of disabling it is worth the small convenience.

**Comment by tchyra** [comment]
Thank you for the explanation, I've made my case for it and I won't insist further. I've already changed all occurrences in my current project to `{ disabled: !isEnabled }`, this is by no means a deal-breaker as the effect works great. Thank you once again!

**Comment by justintaddei** [comment]
I've decided I'm going to leave the current API as is, for the reasons outlined above. With that said, I try to be open to everyone's suggestions, so if you have any other ideas for the project, please open another issue :)
